// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseAlert: typeof import('./components/base/BaseAlert.vue')['default']
    BaseAvatar: typeof import('./components/base/BaseAvatar.vue')['default']
    BaseBadge: typeof import('./components/base/BaseBadge.vue')['default']
    BaseBadgeImg: typeof import('./components/base/BaseBadgeImg.vue')['default']
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseCard: typeof import('./components/base/BaseCard.vue')['default']
    BaseCheckBox: typeof import('./components/base/BaseCheckBox.vue')['default']
    BaseInput: typeof import('./components/base/BaseInput.vue')['default']
    BaseInputBbCode: typeof import('./components/base/BaseInputBbCode.vue')['default']
    BasePagination: typeof import('./components/base/BasePagination.vue')['default']
    BaseSelect: typeof import('./components/base/BaseSelect.vue')['default']
    BaseSpinner: typeof import('./components/base/BaseSpinner.vue')['default']
    BaseTextarea: typeof import('./components/base/BaseTextarea.vue')['default']
    BaseUploadFile: typeof import('./components/base/BaseUploadFile.vue')['default']
    IconClose: typeof import('./components/icon/IconClose.vue')['default']
    IconLogout: typeof import('./components/icon/IconLogout.vue')['default']
    PageFurnidata: typeof import('./pages/PageFurnidata.vue')['default']
    PageIndex: typeof import('./pages/PageIndex.vue')['default']
    PageNotFound: typeof import('./pages/PageNotFound.vue')['default']
    PageUploadFurni: typeof import('./pages/PageUploadFurni.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheButtonReturn: typeof import('./components/TheButtonReturn.vue')['default']
    TheLogin: typeof import('./components/TheLogin.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    TheTopNofitications: typeof import('./components/TheTopNofitications.vue')['default']
  }
}
